### ISSUE TITLE
本地开发时，打开项目后控制台偶尔会抛异常

### ISSUE THREAD

**Issue by xiaohulu** [blocklang/blocklang.com#173]
虽然抛异常，但页面加载正常。

```text
java.nio.file.AccessDeniedException: C:\Program Files\Git\mingw64\etc\.probe-4fd4c9c2-5360-4d80-9b4a-7a884b2b30a0
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[na:na]
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[na:na]
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[na:na]
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235) ~[na:na]
	at java.base/java.nio.file.Files.newByteChannel(Files.java:373) ~[na:na]
	at java.base/java.nio.file.Files.createFile(Files.java:650) ~[na:na]
	at org.eclipse.jgit.util.FS$FileStoreAttributeCache.<init>(FS.java:234) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
	at org.eclipse.jgit.util.FS$FileStoreAttributeCache.getFsTimestampResolution(FS.java:211) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
	at org.eclipse.jgit.util.FS.getFsTimerResolution(FS.java:321) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
	at org.eclipse.jgit.internal.storage.file.FileSnapshot.<init>(FileSnapshot.java:186) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
	at org.eclipse.jgit.internal.storage.file.FileSnapshot.save(FileSnapshot.java:122) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
	at org.eclipse.jgit.storage.file.FileBasedConfig.load(FileBasedConfig.java:156) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
	at org.eclipse.jgit.internal.storage.file.FileRepository.loadSystemConfig(FileRepository.java:245) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
	at org.eclipse.jgit.internal.storage.file.FileRepository.<init>(FileRepository.java:203) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
	at org.eclipse.jgit.storage.file.FileRepositoryBuilder.build(FileRepositoryBuilder.java:88) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
	at org.eclipse.jgit.storage.file.FileRepositoryBuilder.create(FileRepositoryBuilder.java:108) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
	at com.blocklang.core.git.GitFile.execute(GitFile.java:53) ~[classes/:na]
	at com.blocklang.core.git.GitUtils.getFiles(GitUtils.java:198) ~[classes/:na]
	at com.blocklang.develop.service.impl.ProjectResourceServiceImpl.lambda$4(ProjectResourceServiceImpl.java:112) ~[classes/:na]
	at java.base/java.util.Optional.map(Optional.java:265) ~[na:na]
	at com.blocklang.develop.service.impl.ProjectResourceServiceImpl.findChildren(ProjectResourceServiceImpl.java:112) ~[classes/:na]
```

**Comment by xiaohulu** [comment]
可能是一个 jgit 的 bug
https://github.com/diffplug/spotless/issues/410

**Comment by xiaohulu** [comment]
升级后未发现此异常
