### ISSUE TITLE
页面设计器中点击保存按钮后返回 405 错误

### ISSUE THREAD

**Issue by xiaohulu** [blocklang/blocklang.com#321]
```
请求网址:https://localhost/
请求方法:PUT
远程地址:[::1]:443
状态码:
405
版本:HTTP/1.1
Referrer 政策:no-referrer-when-downgrade
```

**Comment by xiaohulu** [comment]
```
java.lang.IllegalArgumentException: 项目拥有者的登录名不能为空
	at org.springframework.util.Assert.hasLength(Assert.java:239) ~[spring-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at com.blocklang.develop.model.ProjectContext.<init>(ProjectContext.java:36) ~[classes/:na]
	at com.blocklang.develop.service.impl.ProjectResourceServiceImpl.lambda$21(ProjectResourceServiceImpl.java:567) ~[classes/:na]
	at java.base/java.util.Optional.map(Optional.java:258) ~[na:na]
	at com.blocklang.develop.service.impl.ProjectResourceServiceImpl.updatePageFileInGit(ProjectResourceServiceImpl.java:566) ~[classes/:na]
```

**Comment by xiaohulu** [comment]
```
org.postgresql.util.PSQLException: 错误: 重复键违反唯一约束"pk_page_widget_attr_value"
  详细：键值"(dbid)=(b2a75980f986449e8bce10214f80ddc7)" 已经存在
```
