### ISSUE TITLE
当指定的文件路径不存在时，需要在控制台显示提示信息

### ISSUE THREAD

**Issue by xiaohulu** [blocklang/blocklang.com#333]
当前是后台报错，前台不相应。

```text
java.nio.file.FileSystemException: E:\data\blocklang\...\publishLogs: Unable to determine if root directory exists
	at java.base/java.nio.file.Files.createDirectories(Files.java:775) ~[na:na]
	at com.blocklang.marketplace.task.TaskLogger.<init>(TaskLogger.java:40) ~[classes/:na]
	at com.blocklang.marketplace.service.impl.PublishServiceImpl.publish(PublishServiceImpl.java:83) ~[classes/:na]
	at com.blocklang.marketplace.service.impl.PublishServiceImpl.asyncPublish(PublishServiceImpl.java:68) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
```

**Comment by xiaohulu** [comment]
有两处需添加校验：

1. 发布项目
1. 注册组件
