### ISSUE TITLE
加载小程序的 app 页面时报错

### ISSUE THREAD

**Issue by xiaohulu** [blocklang/blocklang.com#495]
```text
Resolved [org.springframework.web.bind.MissingServletRequestParameterException: Required String parameter 'repo' is not present]
```

**Comment by xiaohulu** [comment]
问题 2

```
java.lang.NullPointerException: null
	at com.blocklang.develop.service.impl.ProjectResourceServiceImpl.lambda$39(ProjectResourceServiceImpl.java:884) ~[classes/:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1624) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
	at com.blocklang.develop.service.impl.ProjectResourceServiceImpl.getPageWidgets(ProjectResourceServiceImpl.java:947) ~[classes/:na]
	at com.blocklang.develop.service.impl.ProjectResourceServiceImpl.getPageModel(ProjectResourceServiceImpl.java:808) ~[classes/:na]
	at com.blocklang.develop.controller.PageDesignerController.getPageModel(PageDesignerController.java:133) ~[classes/:na]
	
```
